-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 创建 images 存储桶（public 访问）
INSERT INTO storage.buckets (id, name, public)
VALUES ('images', 'images', true)
ON CONFLICT (id) DO NOTHING;

-- 创建 images 元数据表
CREATE TABLE IF NOT EXISTS public.images (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  filename TEXT NOT NULL,
  original_name TEXT NOT NULL,
  file_size INTEGER NOT NULL,
  mime_type TEXT NOT NULL,
  storage_path TEXT NOT NULL,
  public_url TEXT NOT NULL,
  width INTEGER,
  height INTEGER,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 存储桶 RLS 策略
CREATE POLICY "Allow anonymous uploads" ON storage.objects
  FOR INSERT TO anon WITH CHECK (bucket_id = 'images');
CREATE POLICY "Allow anonymous select" ON storage.objects
  FOR SELECT TO anon USING (bucket_id = 'images');
CREATE POLICY "Allow anonymous delete" ON storage.objects
  FOR DELETE TO anon USING (bucket_id = 'images');

-- images 表 RLS
ALTER TABLE public.images ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow anonymous access" ON public.images
  FOR ALL TO anon USING (true) WITH CHECK (true);